### ISSUE TITLE
催更催更，没效果

### ISSUE THREAD

**Issue by nonomal** [jerryshell/kutt-appinn-net-demon-mirror#1]
如题
测试地址:
https://www.appinn.com/1password-8-for-ios-testflight/
![image](https://user-images.githubusercontent.com/30823641/163529494-55cf9e2e-10e1-4256-8ea3-00d484a1a25f.png)

**Comment by jerryshell** [comment]
提供一下你使用的「浏览器信息」和「没效果的页面链接」

**Comment by jerryshell** [comment]
你使用的是什么浏览器？

**Comment by nonomal** [comment]
onload: function(res){
              console.log("33",res)
                            if(res.status === 200){
                                console.log('成功')
                               kuttAElement.textContent = res.finalUrl;
                            }else{
                                console.log('失败')
                                console.log(res)
                            }
                        },

**Comment by nonomal** [comment]
我自己改好了，用的edge
onload 方法，话说你怎么是onerror

**Comment by jerryshell** [comment]
因为我用的是 Chrome，Chrome 浏览器不走 onload，然后我换了个方法，直接在 error 信息里拿 URL 😂

**Comment by nonomal** [comment]
那为了兼容，onload也写了吧，哈哈，onerror很奇怪，chrome为啥走onerror。。不懂

**Comment by jerryshell** [comment]
现在应该好了
